theme: jekyll-theme-clean-blog

title:              IAI-HRC
email:              yuqian.lu@auckland.ac.nz
description:        The HRC project at the Industrial AI Research Team@UoA
author:             IAI-HRC
baseurl:            
url:                "https://iai-hrc.github.io"

# Social Profiles
github_username:    IAI-HRC-github

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
##  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

